name: Node.js CI

on: [push, pull_request]

jobs:
  compile:
    name: Test Webpack Production Compile
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install locked dependencies
        run: npm ci

      - run: npm run compile
      
  make-macos:
    needs: [compile]

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install locked dependencies
        run: npm ci

      - name: Run Electron Forge make
        run: npm run make

  make-linux:
    needs: [compile]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install locked dependencies
        run: npm ci

      - name: Package application
        run: npm run package

  make-windows:
    needs: [compile]

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install locked dependencies
        run: npm ci

      - name: Run Electron Forge make
        run: npm run make
