name: Node.js CI

on: [push, pull_request]

jobs:
  compile:
    name: Test Webpack Production Compile
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install locked dependencies
        run: npm ci

      - run: npm run compile
      
  make-macos:
    needs: [compile]

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install locked dependencies
        run: npm ci

      - name: Compile Typescript
        run: npm run compile

      - name: Make application
        run: npm run make # ./out/beryl-darwin-x64/ or ./out/make/zip/darwin/x64/<zip file>

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: beryl-macos-standalone-archive
          path: ${{ github.workspace }}/out/make/zip/darwin/x64

  make-linux:
    needs: [compile]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install locked dependencies
        run: npm ci

      - name: Package application
        run: npm run package # ./out/beryl-linux-x64/

      - name: Create standalone binary archive
        uses: ihiroky/archive-action@v1
        with:
          root_dir: out/
          file_path: linux-standalone.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: beryl-linux-standalone-archive
          path: ${{ github.workspace }}/linux-standalone.tar.gz

  make-windows:
    needs: [compile]

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install locked dependencies
        run: npm ci

      - name: Package application
        run: npm run package

      - name: Zip standalone binary archive
        uses: ihiroky/archive-action@v1
        with:
          root_dir: out/beryl-win32-x64/
          file_path: windows-standalone.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: beryl-windows-standalone-archive
          path: ${{ github.workspace }}/windows-standalone.zip

  create-windows-installer:
    # needs: [make-windows]
    runs-on: windows-latest

    steps:
      - run: ISCC
        shell: cmd
