# TODO: Move this functionality to node_js.yaml to keep everything together
name: Create GitHub Release

on:
  push:
    tags: 'v*.*.*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Set PREREL environment variable
        env:
          TAG: ${{ github.ref }}
        run: echo "PREREL=$(if [[ $TAG =~ "alpha" ]] || [[ $TAG =~ "beta" ]] || [[ $TAG =~ "rc" ]]; then echo "true"; else echo "false"; fi;)" >> $GITHUB_ENV

      - name: Sanitize github.ref
        run: echo "TAG_VERSION=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV
        # Normally to remove refs/tags/ I just use 10, but in this case I also
        # want to remove the first character of the tag which should be a 'v' so here the length is 11.

      - name: Create Release with Assets
        id: release
        uses: softprops/action-gh-release@v1
        with:
          name: Version ${{ env.TAG_VERSION }}
          draft: false
          prerelease: ${{ env.PREREL }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
